#!/bin/bash

. $(dirname $0)/functions

curl_am_optee_vchong(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/vchong/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

curl_am_optee_optee(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/OP-TEE/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG KMGK master                    #####
#######################################################
## KM mods
curl_am_optee_vchong device-linaro-hikey 1fbbbbfc95c98075750cb73e02e380cf35f29e42 device/linaro/hikey

## print version_str on not_match
curl_am_optee_vchong system_keymaster 2afb818c88fe7fd0efb41ff89aa73a1904580df2 system/keymaster

## convert alphabetic version to number
curl_am_optee_vchong system_keymaster d0cdd9ea97cf125ff62fb41d124bca531594fe7e system/keymaster

## platform_versions.txt: change alphabet to number
#curl_am_optee_vchong cts 25005e189023ef06946df6b199cd3ab274cd4cf7 cts

## config.mk: do NOT obsolete PATH
#curl_am_optee_vchong platform_build cc0b836c5b7a3d59b84358b726a93ba49342dcc7 build/make

## Revert "config.mk: do NOT obsolete PATH"
#curl_am_optee_vchong platform_build a8d12b8c381c7e3a55bcb10e72de2d45a93bc58d build/make

## version_defaults.mk: change alphabet to number
#curl_am_optee_vchong platform_build cda98b9fca9287282cb7b13c579f2331a2a912f9 build/make

## config.mk: do NOT obsolete export
curl_am_optee_vchong platform_build 1861236194183e7d843f1f66ba632bd331a8f97c build/make
