#!/bin/bash

. $(dirname $0)/functions

curl_am_optee_vchong(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/vchong/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

curl_am_optee_optee(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/OP-TEE/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG KMGK O                         #####
#######################################################
## KM mods
curl_am_optee_vchong device-linaro-hikey 33ba1801504fa2eebd1e8e8533f6ea36c70c2259 device/linaro/hikey
