#!/bin/bash

set -e

CPUS=${CPUS:-$(grep processor /proc/cpuinfo |wc -l)}
#CPUS=${CPUS:-$(getconf _NPROCESSORS_ONLN)}
dbg=false

# sync*.sh get_config, build*.sh doesn't!
# build*.sh only export_config
function get_config(){
	if [ -d abc ]; then
		echo "android-build-configs (abc) exists"
		echo "git pull abc"
		pushd abc
		git pull
		popd
	else
		echo "Get android-build-configs (abc)"
		git clone https://android-git.linaro.org/git/android-build-configs.git abc
	fi
}

function export_config(){
    echo "Exporting configs from abc/lcr-reference-${board}-${version}"

    while read line; do
        if ! echo ${line} |grep -q '^#'; then
	    echo "export ${line}"
            eval "export ${line}"
        fi
    done < abc/lcr-reference-${board}-${version}
}

function get_manifest_groups(){
    pushd .repo/manifests
    groups=$(git config --get manifest.groups)
    if [ -z "${groups}" ]; then
        groups_opt=""
    else
        groups_opt="-g ${groups}"
    fi
    popd
    echo "${groups_opt}"
}
