#!/bin/bash

set -e

CPUS=${CPUS:-$(grep processor /proc/cpuinfo |wc -l)}
#CPUS=${CPUS:-$(getconf _NPROCESSORS_ONLN)}
dbg=false

# sync*.sh get_config, build*.sh doesn't!
# build*.sh only export_config
function get_config(){
	if [ -d abc ]; then
		echo "android-build-configs (abc) exists"
		echo "git pull abc"
		pushd abc
		git pull
		popd
	else
		echo "Get android-build-configs (abc)"
		git clone https://android-git.linaro.org/git/android-build-configs.git abc
	fi
}

function export_config(){
    local file=${board}-optee-${version}

    echo "Remove ${file}-pullreqs from abc/${file} before exporting configs"
    sed -e "s/${file}-pullreqs //g" abc/${file} > abc/foo
    mv abc/foo abc/${file}

    echo "Exporting configs from abc/${file}"

    while read line; do
        if echo "${line}"|tr -d '[:blank:]'|grep -q '^$'; then
            continue
        fi
        if ! echo ${line} |grep -q '^#'; then
            echo "export ${line}"
            eval "export ${line}"
        fi
    done < abc/${file}
}

function get_manifest_groups(){
    pushd .repo/manifests
    groups=$(git config --get manifest.groups)
    if [ -z "${groups}" ]; then
        groups_opt=""
    else
        groups_opt="-g ${groups}"
    fi
    popd
    echo "${groups_opt}"
}
